### PR TITLE
Quarto blog refactor

### PR DESCRIPTION
**Pull request by eveilyeverafter**
This branch reconfigures scratch space. It uses Quarto Blog and Github actions to automatically render the blog component of scratch space. Following the PR and merge, this framework serves to bring our "scratch space content" (e.g., tips for using and analyzing CosMx data) to individuals 1) with coding experience and 2) who are less analytical and computational but who would like to learn how we analyze data. For the former, the repo with code is still [publicly available](https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space){target="_blank"}. For the latter, we are now using a [themed blog that's part of the repo](https://nanostring-biostats.github.io/CosMx-Analysis-Scratch-Space/about.html){target="_blank"}.

Here's an image of the _About_ page: 

about page

In addition to the automatic rendering, using the Quarto Blog format has several additional benefits: 

- Searchable website (using the magnifying glass which is located on the upper right)
- Consistent aesthetics (nanostring colors, etc.) but author-level freedom to write in their own style.
- Blogs with dates added, modified, authors, author's github handles
- Blogs are tagged with 'categories' so that readers can search the growing blog with post on a particular topic (e.g., all cell typing posts, all napari posts)
- Blog gallery with preview images in addition to the original Table of Contents layout (see next image)
- The repo makes use of package isolation principles via `renv` making it easier for anyone to reproduce the code
- The blog posts can remain text files, switching vanilla markdown (.md) with a similar format (.qmd [.rmd should be okay too]). 
- Or the blog posts can be code can be executed within the qmd files during time of rendering (using the configured ubuntu OS in github) and larger computations can be "frozen" to mitigate unneeded re-computes
- Layout of website also includes footers for LEGAL (copy/paste from `main`) and "how to contribute" (still under construction)
- Layout has link to `Code` on the upper left that points the reader to the codebase. 
- In turn, the README.md that is in the parent level folder points readers to the corresponding website

blog layout

While this PR will introduce several file changes, many of which are part of the theming and formatting and are not expected to change frequently. Here's I'll touch on a few files. 

- .github/workflows/publish.yml: This file is needed for github to render the site. Installs specific operating system (ubuntu), quarto, R, reads the `renv` folder to install the necessary versions of packages, and executes the qmd files within the `posts` folder.
- _quarto.yml: this yaml file orchestrates the type of quarto blog, and non-blog-related files (e.g., license, about.qmd)
- custom.scss: this sassy css file modifies the default 'minty' theme to branded colors.
- `_code`: this is a copy/paste of the main branch's `code` folder as of a few days ago. The `_` prefix tells quarto to ignore the contents. 

Note: Right now we are rendering the [website](https://nanostring-biostats.github.io/CosMx-Analysis-Scratch-Space/about.html){target="_blank"} on the quarto_blog_refactor branch (which is specified in the publish.yml file. Once merged, we will need to point it to the main.

### CODE REVIEW

**Comment by patrickjdanaher** [comment]
Broad comments:
- Looks so much better - very excited to make this whole thing more professional and user-friendly. 
- the github readme probably needs a little more for folks. I think we need: 1. the old preamble ("This repo is here to accelerate analysis of CosMx datasets. It contains code and writeups addressing..."). 2. correct the link to use the new io page (from this repo). 3. Expand the explanation: "Code and mini-packages can be found in the _code directory. However, the easiest browsing is through the blog page."
- I had trouble finding the table of contents (here: https://nanostring-biostats.github.io/CosMx-Analysis-Scratch-Space/about.html). Can we change the name of that hyperlink to something more descriptive, e.g. "Browse posts by topic"
- Sorry to be persnickety about aesthetics: for the banner image (the negative space words atop the stained glass image), can you make the words smaller, and spell out the full name "CosMx Analysis Scratch Space"? I'm imagining it fitting across the top of the image, only covering the top ~25% of the banner. 
- head of the blog page: "CosMx Analysis Scratch Space", not "Nanostring scratch space"
- when I try links from blog posts to the github code, they all give me a 404. 
- more aesthetics: the chartreuse links somehow look less professional to me - can we revert to standard blue?

**Comment by eveilyeverafter** [comment]
@patrickjdanaher for your 3rd bullet point

> I had trouble finding the table of contents (here: https://nanostring-biostats.github.io/CosMx-Analysis-Scratch-Space/about.html). Can we change the name of that hyperlink to something more descriptive, e.g. "Browse posts by topic"

Do you mean having text on the upper right say "Browse posts by topic" or do you mean replacing the "Table of Contents" with "Browse posts by topic"?

**Comment by eveilyeverafter** [comment]
> Looks so much better - very excited to make this whole thing more professional and user-friendly.

Thanks.

> the github readme probably needs a little more for folks. I think we need: 1. the old preamble ("This repo is here to accelerate analysis of CosMx datasets. It contains code and writeups addressing..."). 2. correct the link to use the new io page (from this repo). 3. Expand the explanation: "Code and mini-packages can be found in the _code directory. However, the easiest browsing is through the blog page."

I updated the readme. Commit = 0ab527f7edfab4aadf9065a25653e789f0f296f5

> Sorry to be persnickety about aesthetics: for the banner image (the negative space words atop the stained glass image), can you make the words smaller, and spell out the full name "CosMx Analysis Scratch Space"? I'm imagining it fitting across the top of the image, only covering the top ~25% of the banner.

No problem. Do you like one of these options? 

image


> head of the blog page: "CosMx Analysis Scratch Space", not "Nanostring scratch space"

Done. Commit = 58614023844b4783a2d30d2796c3a75b7fe2fff3

> when I try links from blog posts to the github code, they all give me a 404.

This was expected. They are still linking to the test repo. I think I fixed them all. Commit = 8cd693bab614f051708c9a3021390c367e96e7ec

> more aesthetics: the chartreuse links somehow look less professional to me - can we revert to standard blue?

Done. Commit = 36cd04f6454f33e0fd81ba67b1f52dff94878f78

**Comment by eveilyeverafter** [comment]
@patrickjdanaher, I updated the final two requests. Can you approve if applicable?

**Comment by eveilyeverafter** [comment]
I switched deployment to be from the main branch instead of the feature branch (ahead of merge). A deployment error is expected until the merge is complete.

**Review by patrickjdanaher — APPROVED** [review]
A few broken links from blog -> code to fix, then good to go!

**Comment by eveilyeverafter** [comment]
URLs should work following the merge to Main.

**Pull request merged**
